# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'


development:
  url:  <%= ENV["DATABASE_URL"] || "mysql2://root@localhost" %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: dev01

test:
  url:  <%= ENV["DATABASE_URL"] || "mysql2://root@localhost" %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: test01

